protected/controllers/BookingController.php
<?php

/**
 * Class BookingController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class BookingController extends Controller
{
    public $defaultAction = 'manage';

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['manage', 'create', 'update', 'delete']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionCreate()
    {
        $booking = new CommBooking('create');
        $booking->unsetAttributes();

        if(isset($_POST['CommBooking'])) {
            $booking->setAttributes($_POST['CommBooking']);

            // @fixme ua_id
            $booking->ua_id = Yii::app()->user->id;
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($booking);
            Yii::app()->end();
        }

        if(isset($_POST['CommBooking']) && !isset($_POST['ajax'])) {
            if($booking->save()) {
                $this->redirect(['booking/update', 'id' => $booking->id]);
            }
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('create', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('create', [
                'booking' => $booking
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $booking = CommBooking::model()->findByPk($id);
        if(is_null($booking)) throw new CHttpException(403, 'Not Found');
        if($booking->stat == CommBooking::STAT_DONE) $this->redirect(['/booking/manage']);

        if(isset($_POST['CommBooking'])) {
            $booking->setAttributes($_POST['CommBooking']);
            $booking->ua_id = Yii::app()->user->id;

            $booking->save();
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($booking);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('update', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('update', [
                'booking' => $booking
            ]);
        }
    }

    public function actionDelete($id)
    {
        $booking = CommBooking::model()->findByPk($id);
        if(!is_object($booking)) throw new CHttpException('Not Found');

        CommBooking::model()->deleteByPk($id);
    }

    public function actionManage()
    {
        $booking = new CommBooking('manage');
        $booking->unsetAttributes();

        if(isset($_GET['CommBooking'])) {
            $booking->setAttributes($_GET['CommBooking']);
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('manage', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('manage', [
                'booking' => $booking
            ]);
        }
    }
}

protected/controllers/CompanyController.php
<?php

/**
 * Class CompanyController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class CompanyController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['browse', 'detail']
            ),
            array(
                'allow',
                'roles'   => [UserAccount::IT],
                'actions' => ['manage', 'relate']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionBrowse()
    {
        $query = null;
        if(isset($_GET['query'])) {
            $query = $_GET['query'];
        }

        $criteria = new CDbCriteria();
        $criteria->condition = 'name LIKE :name';
        $criteria->params = ['name' => "%$query%"];
        $criteria->limit = 10;
        $company = CommMigrateCompany::model()->findAll($criteria);

        $result = array();
        foreach($company as $i => $c) {
            $result[$i]['text'] = $c->name;
            //$result[$i]['code'] = $c->code;
            $result[$i]['id'] = $c->id;
        }

        header('Content-type: application/json');
        echo json_encode($result);
    }

    public function actionDetail($id)
    {
        $company = CommMigrateCompany::model()->findByPk($id);
        if(!is_object($company)) $o = ['id' => 0, 'text' => 'Not Found'];
        else $o = ['id' => $company->id, 'text' => $company->name];

        header('Content-type: application/json');
        echo json_encode($o);
    }

    public function actionManage()
    {}

    public function actionRelate()
    {
        set_time_limit(0);

        $counter = 0;
        $eCusts = DataOutsideCompany::model()->findAll();
        $sCusts = CHtml::listData(CommMigrateCompany::model()->findAll(), 'code', 'name');

        foreach($eCusts as $eCust) {
            if(!array_key_exists($eCust->CUSTCODE, $sCusts)) {
                $company = new CommMigrateCompany();
                $company->code = $eCust->CUSTCODE;
                $company->name = $eCust->CUSNAME;
                $company->save(FALSE);
                $counter++;
            }
        }

        echo $counter;
    }
}

protected/controllers/RequestController.php
<?php

/**
 * Class RequestController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class RequestController extends Controller {
    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['manage', 'browse', 'create', 'update', 'delete']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionCreate($id)
    {
        $request = new CommBookingRequest('create');
        $request->unsetAttributes();

        $request->ua_id = Yii::app()->user->id;
        $request->cb_id = $id;

        if(isset($_POST['CommBookingRequest'])) {
            $request->setAttributes($_POST['CommBookingRequest']);

            if($request->save()) {}
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($request);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('create', [
                'request' => $request
            ], false, true);
        } else {
            $this->render('create', [
                'request' => $request
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $request = CommBookingRequest::model()->findByPk($id);
        if(is_null($request)) throw new CHttpException(403, 'Not Found');

        if(isset($_POST['CommBookingRequest'])) {
            $request->setAttributes($_POST['CommBookingRequest']);
            $request->ua_id = Yii::app()->user->id;
            $request->save();
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($request);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('update', [
                'request' => $request
            ], false, true);
        } else {
            $this->render('update', [
                'request' => $request
            ]);
        }
    }

    public function actionDelete($id)
    {
        $booking = CommBookingRequest::model()->findByPk($id);
        if(!is_object($booking)) throw new CHttpException('Not Found');
        if($booking->stat === CommBookingRequest::STAT_DONE) throw new CHttpException('Request yang sudah dicetak tidak dapat dihapus', 403);

        CommBookingRequest::model()->deleteByPk($id);
    }

    public function actionManage($id)
    {
        $request = new CommBookingRequest('manage');
        $request->unsetAttributes();

        if(isset($_GET['CommBookingRequest'])) {
            $request->setAttributes($_GET['CommBookingRequest']);
        }

        $request->cb_id = $id;

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('manage', [
                'request' => $request
            ], false, true);
        } else {
            $this->render('manage', [
                'request' => $request
            ]);
        }
    }

    public function actionBrowse()
    {
        $request = new CommBookingRequest('browse');
        $request->unsetAttributes();

        if(isset($_GET['CommBookingRequest'])) {
            $request->setAttributes($_GET['CommBookingRequest']);
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('browse', [
                'request' => $request
            ], false, true);
        } else {
            $this->render('browse', [
                'request' => $request
            ]);
        }
    }
}

protected/views/booking/_form.php
<?php
/**
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
?>

<?php Yii::app()->getClientScript()->registerScript('comm-booking-form', '
//$("#CommBooking_co_id").typeahead({
//    name: "company",
//    remote: "' . Yii::app()->request->baseUrl . '/index.php/company/browse?query=%QUERY",
//    template: "<p>{{name}} – <strong>{{code}}</strong></p>",
//    engine: Hogan
//});
//$("#CommBooking_sa_id").typeahead({
//    name: "sales",
//    remote: "' . Yii::app()->request->baseUrl . '/index.php/account/sales?query=%QUERY",
//    template: "<p>{{name}} – <strong>{{code}}</strong></p>",
//    engine: Hogan
//});
'); ?>

<?php $form = $this->beginWidget('ActiveForm', [
    'id' => 'comm-booking-form',
    'htmlOptions' => ['class' => 'form-horizontal'],
    'enableClientValidation' => FALSE,
    'enableAjaxValidation' => TRUE,
    'clientOptions'=>array(
        'validateOnSubmit' => TRUE,
        'validateOnChange' => FALSE,
    ),
]); ?>
<fieldset>
    <legend>Booking</legend>
<div class="form-group">
    <?php echo $form->label($booking, 'name', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php echo $form->textField($booking, 'name', ['class' => 'form-control']) ?>
        <?php echo $form->error($booking, 'name', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($booking, 'sa_id', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php //echo $form->textField($booking, 'sa_id', ['class' => 'form-control']) ?>
        <?php echo $form->dropDownList($booking, 'sa_id', CHtml::listData(UserAccount::model()->findAll('division = 2'), 'id', 'realname'), ['style' => 'min-width: 200px']) ?>
        <?php echo $form->error($booking, 'sa_id', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($booking, 'co_id', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php //echo $form->textField($booking, 'co_id', ['class' => 'form-control']) ?>
        <?php echo $form->textField($booking, 'co_id', ['style' => 'min-width: 250px;']) ?>
        <?php echo $form->error($booking, 'co_id', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($booking, 'stat', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php echo $form->dropDownList($booking, 'stat', CommBooking::getStatList(), ['class' => 'form-control']) ?>
        <?php echo $form->error($booking, 'stat', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($booking, 'editions', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <div class="row">
            <div class="col-xs-12">
                <a id="edition_checkall" href="javascript:;">Check All</a>
                &dash;
                <a id="edition_uncheckall" href="javascript:;">Uncheck All</a>
            </div>
        </div>
        <?php echo $form->checkBoxList($booking, 'editions', NewsEdition::getOptionList()) ?>
        <?php echo $form->error($booking, 'editions', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
        <?php echo CHtml::submitButton('Submit', ['class' => 'btn btn-primary']); ?>
    </div>
</div>
</fieldset>
<?php $this->endWidget(); ?>
<script type="text/javascript">
    $(function() {
        $("#edition_checkall").click(function() {
            $("#CommBooking_editions > input").each(function(idx, val) {
                $(this).prop("checked", true);
            });
        });
        $("#edition_uncheckall").click(function() {
            $("#CommBooking_editions > input").each(function(idx, val) {
                $(this).prop("checked", false);
            });
        });
        $("#CommBooking_sa_id").select2();
        $("#CommBooking_co_id").select2({
            data: [],
            ajax: {
                url: '<?php echo $this->createUrl('/company/browse'); ?>',
                dataType: 'json',
                data: function(term, page) {
                    return {
                        query: term
                    };
                },
                results: function(data, page) {
                    return {
                        results: data
                    };
                }
            },
            initSelection: function(e, c) {
                var id = $(e).val();
                if(id !== "") {
                    return $.ajax({
                        url: "<?php echo $this->createUrl('/company/detail'); ?>",
                        type: "GET",
                        dataType: "json",
                        data: {
                            id: id
                        },
                        success: function(data) {
                            console.log(data);
                            $("#CommBooking_co_id").select2("data", data);
                        }
                    });
                }
            }
        });
    });
</script>

protected/views/booking/create.php
<div class="row">
    <div class="col-xs-12">
        <?php $this->renderPartial('_form', ['booking' => $booking, 'create' => false]); ?>
    </div>
</div>

protected/views/booking/manage.php
<?php
/**
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
?>

<?php
Yii::app()->getClientScript()->registerScript('comm-booking-request-manage-page', '
    function _afterAjaxUpdate(id, data) {
        //$("#CommBookingRequest_publish_at_browse").datepicker();
    };
');
?>

<div class="row"><div class="col-xs-12">
<?php $this->widget('GridView', [
    'id' => 'comm-booking-manage-grid',
    'dataProvider' => $booking->manage(),
    'filter' => $booking,
    'afterAjaxUpdate' => '_afterAjaxUpdate',
    'template' => '{items} {pager}',
    'columns' => [
        [
            'name' => 'id',
            'value' => '$data->id'
        ],
        [
            'name' => 'ua_username',
            'value' => '$data->ua->username',
            'header' => 'PIC'
        ],
        [
            'name' => 'name',
            'value' => '$data->name'
        ],
        [
            'type' => 'raw',
            'name' => 'stat',
            'value' => 'CommBookingRequest::getStatHtml($data->stat)',
            'filter' => CommBookingRequest::getStatList()
        ],
        [
            'class' => 'ButtonColumn',
            'template' => '{update} {delete}',
            'buttons' => [
                'update' => [
                    'visible' => '$data->stat != CommBooking::STAT_DONE'
                ],
                'delete' => [
                    'visible' => '$data->stat != CommBooking::STAT_DONE'
                ]
            ]
        ]
    ]
]); ?>
</div></div>

protected/views/booking/update.php
<?php Yii::app()->getClientScript()->registerScript('comm-booking-request-load', '
$("#comm-booking-request-manage-page").load("'. $this->createUrl('request/manage', ['id' => $booking->id]) .'");
$("#comm-booking-request-create-page").load("'. $this->createUrl('request/create', ['id' => $booking->id]) .'");

$(document).on("click", "#comm-booking-request-manage-grid .table .update", function() {
    $("#comm-booking-request-create-page").load($(this).attr("href"));
    return false;
});
'); ?>

<div class="row">
    <div class="col-sm-6">
        <?php $this->renderPartial('_form', ['booking' => $booking, 'create' => false]); ?>
    </div>
    <div id="comm-booking-request-create-page" class="col-sm-6"></div>
</div>

<div class="row">
    <div id="comm-booking-request-manage-page" class="col-lg-12"></div>
</div>