protected/controllers/BookingController.php
<?php

/**
 * Class BookingController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class BookingController extends Controller
{
    public $defaultAction = 'manage';

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['manage', 'create', 'update', 'delete']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionCreate()
    {
        $booking = new CommBooking('create');
        $booking->unsetAttributes();

        if(isset($_POST['CommBooking'])) {
            $booking->setAttributes($_POST['CommBooking']);

            // @fixme ua_id
            $booking->ua_id = Yii::app()->user->id;
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($booking);
            Yii::app()->end();
        }

        if(isset($_POST['CommBooking']) && !isset($_POST['ajax'])) {
            if($booking->save()) {
                $this->redirect(['booking/update', 'id' => $booking->id]);
            }
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('create', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('create', [
                'booking' => $booking
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $booking = CommBooking::model()->findByPk($id);
        if(is_null($booking)) throw new CHttpException(403, 'Not Found');
        if($booking->stat == CommBooking::STAT_DONE) $this->redirect(['/booking/manage']);

        if(isset($_POST['CommBooking'])) {
            $booking->setAttributes($_POST['CommBooking']);
            $booking->ua_id = Yii::app()->user->id;

            $booking->save();
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($booking);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('update', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('update', [
                'booking' => $booking
            ]);
        }
    }

    public function actionDelete($id)
    {
        $booking = CommBooking::model()->findByPk($id);
        if(!is_object($booking)) throw new CHttpException('Not Found');

        CommBooking::model()->deleteByPk($id);
    }

    public function actionManage()
    {
        $booking = new CommBooking('manage');
        $booking->unsetAttributes();

        if(isset($_GET['CommBooking'])) {
            $booking->setAttributes($_GET['CommBooking']);
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('manage', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('manage', [
                'booking' => $booking
            ]);
        }
    }
}

protected/controllers/PlacingController.php
<?php

/**
 * Class PlacingController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class PlacingController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['browse', 'create', 'getter', 'update']
            ),
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI, UserAccount::SL],
                'actions' => ['report', 'render']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionReport($date = null, $page = 0, $ne_id = 1)
    {
        if(isset($_POST['date'])) {
            $date = $_POST['date'];
        }

        $showForm = false;

        if(is_null($date)) {
            $date = date('Y-m-d');
            $showForm = true;
        }

        if(Yii::app()->request->isAjaxRequest) {
            echo $this->createUrl('placing/report', ['date' => $date]);
            Yii::app()->end();
        }

        $data = array(
            'meta' => [],
            'dpage' => [],
            'items' => [],
        );

        $type = date('N', strtotime($date));;
        $dset = CommPlacingDateset::model()->find('date = :date', ['date' => $date]);
        if(is_object($dset)) $type = $dset->type;
        else {
            switch($type) {
                case 5: $type = 1; break;
                case 6:
                case 7: $type = 2; break;
                default: $type = 0;
            }
        }

        $cpages = CommPlacing::pages();
        $data['meta'] = $cpages[$type]['meta'];
        $pages = $cpages[$type][$page]; // @fixme validate page
        $placing = CommBookingPlacing::model()->findAll(array(
            'together' => true,
            'with' => ['br' => ['with' => ['cb']]],
            'condition' => 't.ne_id = :ne_id AND br.publish_at = :publish_at',
            'params' => [
                'ne_id' => $ne_id,
                'publish_at' => $date
            ]
        ));

        foreach($placing as $p) {
            $data['dpage'][$p->page]['page'] = $p->page;
            $data['dpage'][$p->page]['data'][] = [$p->posx, $p->posy];

            $data['items'][$p->page][] = [
                'name' => $p->br->cb->name,
                'page' => $p->page,
                'sizex' => $p->br->sizex,
                'sizey' => $p->br->sizey,
                'color' => $p->br->color
            ];
        }

//        usort($data['items'], function($a, $b) {
//            return strnatcmp($a['page'], $b['page']);
//        });

        // counter
        $data['count'] = 3780 * count($pages) * 2;

        if(!$showForm) {
            $this->setPageTitle("Report for {$date}");
            $this->render('report_body', array(
                'date' => $date,
                'page' => $page,
                'data' => $data,
                'pages' => $pages
            ));
        } else {
            $this->setPageTitle('Partitur');
            $this->render('report_head', array());
        }
    }

    public function actionGetter()
    {
        $placing = new CommBookingPlacing('getter');
        $placing->unsetAttributes();

        if(isset($_POST['CommBookingPlacing'])) {
            $placing->setAttributes($_POST['CommBookingPlacing']);
        }

        $data = base64_encode(json_encode([
            'page' => $placing->page,
            'data' => [
                [hexdec($placing->posx), hexdec($placing->posy)]
            ]
        ]));
        echo $this->createUrl('placing/render', ['size' => 14, 'data' => $data]);
    }

    public function actionRender($data, $size = 14)
    {
        if(is_null($data = json_decode(base64_decode($data), true))) {
            throw new CHttpException(500, 'Kampret Loe');
        } elseif(!is_array($data) || !isset($data['data'])) {
            throw new CHttpException(500, 'Kampret Loe');
        }

        CommPlacing::render($data, $size);
    }

    public function actionBrowse()
    {
        $placing = new CommPlacing('browse');
        $placing->unsetAttributes();

        if(isset($_GET['CommPlacing'])) {
            $placing->setAttributes($_GET['CommPlacing']);
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('browse', [
                'placing' => $placing
            ], false, true);
        } else {
            $this->render('browse', [
                'placing' => $placing
            ]);
        }
    }

    public function actionCreate($ne_id, $br_id)
    {
        $placing = new CommBookingPlacing('create');
        $placing->unsetAttributes();

        // @fixme validate
        $placing->ua_id = Yii::app()->user->id;
        $placing->ne_id = (int) $ne_id;
        $placing->br_id = (int) $br_id;

        if(isset($_POST['CommBookingPlacing'])) {
            $placing->setAttributes($_POST['CommBookingPlacing']);

            if(Yii::app()->request->isAjaxRequest && $placing->save()) {
                echo CActiveForm::validate($placing);
                Yii::app()->end();
            }

            if(!Yii::app()->request->isAjaxRequest && $placing->save()) {
                $this->redirect(['placing/browse']);
                Yii::app()->end();
            }
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($placing);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('create', [
                'placing' => $placing
            ], false, true);
        } else {
            $this->render('create', [
                'placing' => $placing
            ]);
        }
    }

    public function actionUpdate($ne_id, $br_id)
    {
        $placing = CommBookingPlacing::model()->findByAttributes(['ne_id' => $ne_id, 'br_id' => $br_id]);
        // @fixme ada sesuatu yang salah dengan ZEROFILL
        if(is_null($placing)) {
            //echo var_dump($ne_id);
            //throw new CHttpException(403, 'Not Found');
            //Yii::app()->end();
        }
        $placing->posx = sprintf('%02x', $placing->posx);
        $placing->posy = sprintf('%02x', $placing->posy);

        if(isset($_POST['CommBookingPlacing'])) {
            $placing->setAttributes($_POST['CommBookingPlacing']);
            $placing->ua_id = Yii::app()->user->id;

            if(Yii::app()->request->isAjaxRequest && $placing->save()) {
                echo CActiveForm::validate($placing);
                Yii::app()->end();
            }

            if(!Yii::app()->request->isAjaxRequest && $placing->save()) {
                $this->redirect(['placing/browse']);
                Yii::app()->end();
            }
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($placing);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('create', [
                'placing' => $placing
            ], false, true);
        } else {
            $this->render('create', [
                'placing' => $placing
            ]);
        }
    }
}

protected/views/placing/_form.php
<?php
/**
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
?>

<?php $form = $this->beginWidget('ActiveForm', [
    'id' => 'comm-placing-form',
    'htmlOptions' => ['class' => 'form-horizontal'],
    'enableClientValidation' => FALSE,
    'enableAjaxValidation' => TRUE,
    'clientOptions'=>array(
        'validateOnSubmit' => TRUE,
        'validateOnChange' => FALSE,
        'afterValidate' => 'js:function(form, attribute, hasError){'
        .       'if(!hasError) {'
        .           '$.fn.yiiGridView.update("comm-placing-browse-grid");'
        .           '$("#comm-booking-placing-form").load("'. $this->createUrl('placing/update', ['ne_id' => $placing->ne_id, 'br_id' => $placing->br_id]) .'");'
        .           'return false;'
        .      '}'
        .   '}'
    ),
]); ?>

<div class="form-group">
    <?php echo $form->label($placing, 'ns_id', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php echo $form->dropDownList($placing, 'ns_id', NewsSection::getOptionList(), ['class' => 'form-control']) ?>
        <?php echo $form->error($placing, 'ns_id', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($placing, 'page', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php echo $form->textField($placing, 'page', ['class' => 'form-control']) ?>
        <?php echo $form->error($placing, 'page', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($placing, 'posx', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php echo $form->textField($placing, 'posx', ['class' => 'form-control']) ?>
        <?php echo $form->error($placing, 'posx', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <?php echo $form->label($placing, 'posy', ['class' => 'col-xs-4 control-label']); ?>
    <div class="col-xs-8">
        <?php echo $form->textField($placing, 'posy', ['class' => 'form-control']) ?>
        <?php echo $form->error($placing, 'posy', ['class' => 'help-block']); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
        <?php echo CHtml::submitButton('Submit', ['class' => 'btn btn-primary']); ?>
        <?php echo CHtml::link('Render', ['booking/render'], ['class' => 'render btn btn-warning']); ?>
    </div>
</div>

<?php $this->endWidget(); ?>

protected/views/placing/_view.php
<?php Yii::app()->getClientScript()->registerScript('comm-request-view', '
    $(document).on("click", "#comm-placing-form a.render", function() {
        posx = $("#CommBookingPlacing_posx").val();
        posy = $("#CommBookingPlacing_posy").val();

        jQuery.ajax({
            url: "'. $this->createUrl('placing/getter') .'",
            type: "POST",
            data: $("#comm-placing-form").serialize(),
            success: function(data, textStatus, jqXHR) {
                $("#comm-booking-placing-render-view").attr("src", data);
            }
        });
        return false;
    });
'); ?>

protected/views/placing/browse.php
<?php
/**
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
?>

<?php Yii::app()->getClientScript()->registerScript('comm-booking-placing-load', '
$(document).on("click", "#comm-placing-browse-grid table.items .btn-report", function() {
    $("#comm-booking-placing-form").load($(this).attr("href"));
    return false;
});
'); ?>

<div class="row">
    <div id="comm-booking-placing-form" class="col-sm-12"></div>
</div>

<div class="row"><div class="col-xs-12">
<?php $this->widget('GridView', [
    'id' => 'comm-placing-browse-grid',
    'dataProvider' => $placing->browse(),
    'filter' => $placing,
    'afterAjaxUpdate' => '_afterAjaxUpdate',
    'template' => '{items} {pager}',
    'columns' => [
        [
            'name' => 'cb_id',
        ],
        [
            'name' => 'cb_name',
            'value' => '$data->cb->name'
        ],
        [
            'name' => 'cb_username',
            'value' => '$data->cb->ua->username'
        ],
        [
            'name' => 'ne_id',
            'value' => '$data->ne->name',
            'filter' => NewsEdition::getOptionList()
        ],
        [
            'name' => 'br_id',
        ],
        [
            'name' => 'br_page',
            'value' => '$data->br->page'
        ],
        [
            'name' => 'br_sizex',
            'value' => '$data->br->sizex'
        ],
        [
            'name' => 'br_sizey',
            'value' => '$data->br->sizey'
        ],
        [
            'name' => 'br_stat',
            'value' => 'CommBookingRequest::getStatName($data->br->stat)',
            'filter' => CommBookingRequest::getStatList()
        ],
        [
            'name' => 'br_publish_at',
            'value' => '$data->br->publish_at'
        ],
        [
            'name' => 'bp_id',
            'value' => 'is_null($data->bp_id) ? "NULL" : $data->bp->id'
        ],
        [
            'name' => 'bp_page',
            'value' => 'is_null($data->bp_id) ? "NULL" : $data->bp->page'
        ],
        [
            'name' => 'bp_posx',
            'value' => 'is_null($data->bp_id) ? "NULL" : sprintf("%02x", $data->bp->posx)'
        ],
        [
            'name' => 'bp_posy',
            'value' => 'is_null($data->bp_id) ? "NULL" : sprintf("%02x", $data->bp->posy)'
        ],
        [
            'class' => 'ButtonColumn',
            'template' => '{create} {update}',
            'buttons' => array(
                'create' => array(
                    'url' => 'Yii::app()->createUrl(\'placing/create\', array(\'ne_id\' => $data->ne_id, \'br_id\' => $data->br_id))',
                    'imageUrl' => Yii::app()->baseUrl . '/assets/static/images/icons/add.png',
                    'visible' => '$data->bp_id === null',
                    'options' => ['class' => 'btn-report']
                ),
                'update' => array(
                    'url' => 'Yii::app()->createUrl(\'placing/update\', array(\'ne_id\' => $data->ne_id, \'br_id\' => $data->br_id))',
                    'visible' => '$data->bp_id !== null',
                    'options' => ['class' => 'btn-report']
                )
            )
        ]
    ]
]); ?>
</div></div>

protected/views/placing/create.php
<?php $this->renderPartial('_view', ['placing' => $placing]); ?>
<div class="row">
    <div class="col-sm-6">
        <?php $this->renderPartial('_form', ['placing' => $placing]); ?>
    </div>
    <div class="col-sm-6" style="text-align: center;">
        <img id="comm-booking-placing-render-view" style="width: 140px;" />
    </div>
</div>

protected/views/placing/report_body.php
<!--<pre><?php print_r($data); ?></pre>-->

<div class="row">
    <div class="col-12">
        <ul class="placing-pagination">
        <?php for($i=0; $i<$data['meta']['page']; $i++): ?>
            <li><?php echo CHtml::link($i + 1, ['placing/report', 'date' => $date, 'page' => $i], ['class' => 'btn btn-default']); ?></li>
        <?php endfor; ?>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <?php $materi = array(); ?>
        <?php $total_mmk_iklan = 0; ?>
        <?php $total_mmk_page = 0; ?>
        <?php foreach($pages as $key => $page): ?>
        <h3><?php echo CommPlacing::getEditionName($key); ?></h3>
        <ul class="partiture-image clearfix">
            <?php foreach($page as $pa): ?>
            <li>
                <?php foreach($pa as $p): ?>
                <?php
                    $total_mmk_page += 3780;
                    if(isset($data['dpage'][$p])) {
                        echo CHtml::image($this->createUrl('placing/render', ['data' => base64_encode(json_encode($data['dpage'][$p]))]));
                        if(isset($data['items'][$p]) && is_array($data['items'][$p])) {
                            foreach($data['items'][$p] as $item) {
                                $materi[] = $item;
                                $total_mmk_iklan += $item['sizex'] * $item['sizey'];
                            }
                        }
                    } else {
                        echo CHtml::image($this->createUrl('placing/render', ['data' => base64_encode(json_encode(['page' => $p, 'data' => []]))]));
                    }
                ?>
                <?php endforeach; ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endforeach; ?>
    </div>
</div>

<div class="row">
    <div class="col-12 table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Halaman</th>
                    <th>File</th>
                    <th>Ukuran</th>
                    <th>Warna</th>
                    <th>MMK</th>
                </tr>
            </thead>
            <tbody>
            <?php $ct = array(); ?>
            <?php
            usort($materi, function($a, $b) {
                return strnatcmp($a['page'], $b['page']);
            });
            ?>
            <?php foreach($materi as $item): ?>
                <tr>
                    <td><?php echo $item['page']; ?></td>
                    <td><?php echo $item['name']; ?></td>
                    <td><?php echo $item['sizex'] . 'x' . $item['sizey']; ?></td>
                    <td><?php echo CommBookingRequest::getColorName($item['color']); ?></td>
                    <td><?php echo $ct[] = $item['sizex'] * $item['sizey']; ?></td>
                </tr>
            <?php endforeach; ?>
                <tr>
                    <td colspan="4">TOTAL SPACE</td>
                    <td><?php echo $total_mmk_page; ?></td>
                </tr>
                <tr>
                    <td colspan="4">TOTAL SPACE IKLAN</td>
                    <td><?php echo $total_mmk_iklan; ?></td>
                </tr>
                <tr>
                    <td colspan="4">PROSENTASE IKLAN</td>
                    <td><?php echo round(100 * $total_mmk_iklan / $total_mmk_page, 2); ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

protected/views/placing/report_head.php
<?php Yii::app()->getClientScript()->registerScript('comm-booking-placing-report-date', '
    $(function() {
        $("#comm-booking-placing-report-date").datepicker({
            numberOfMonths: 3,
            changeMonth: false,
            changeYear: false,
            onSelect: function(value, date) {
                $.ajax({
                    url: "'. $this->createUrl('placing/report') .'",
                    type: "POST",
                    data: {date: value},
                    success: function(data, textStatus, jqXHR) {
                        $(location).attr("href", data);
                    }
                });
            }
        });
    });
'); ?>

<div class="row">
    <div class="span-12" style="text-align: center">
        <div id="comm-booking-placing-report-date" style="display: inline-block;"></div>
    </div>
</div>

<div id="comm-booking-placing-report-view"></div>

protected/views/placing/update.php
<?php $this->renderPartial('_view', ['placing' => $placing]); ?>
<div class="row">
    <div class="col-sm-6">
        <?php $this->renderPartial('_form', ['placing' => $placing]); ?>
    </div>
    <div class="col-sm-6">
        <img id="comm-booking-placing-render-view" />
    </div>
</div>