protected/controllers/AccountController.php
<?php

/**
 * Class AccountController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class AccountController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT],
                'actions' => ['manage', 'create', 'update', 'delete']
            ),
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['sales']
            ),
            array(
                'allow',
                'users' => ['?'],
                'actions' => ['login']
            ),
            array(
                'allow',
                'users' => ['@'],
                'actions' => ['index', 'logout']
            ),
            array(
                'allow',
                'users' => ['*'],
                'actions' => ['error']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionManage()
    {
        $account = new UserAccount('manage');
        $account->unsetAttributes();

        if(isset($_GET['UserAccount'])) {
            $account->setAttributes($_GET['UserAccount']);
        }

        $this->render('manage', array(
            'account' => $account
        ));
    }

    public function actionCreate()
    {
        $account = new UserAccount('create');
        $account->unsetAttributes();

        if(isset($_POST['UserAccount'])) {
            $account->setAttributes($_POST['UserAccount']);
            $account->password = sha1($account->password);
            if(!Yii::app()->request->isAjaxRequest && $account->save()) {
                $this->redirect(['account/manage']);
            }
        }

        if(Yii::app()->request->isAjaxRequest) {
            echo CActiveForm::validate($account);
            Yii::app()->end();
        }

        $this->render('create', array(
            'account' => $account
        ));
    }

    public function actionUpdate($id)
    {
        $account = UserAccount::model()->findByPk($id);
        if(!is_object($account)) throw new CHttpException(403, 'Not Found');

        if(isset($_POST['UserAccount'])) {
            $account->setAttributes($_POST['UserAccount']);

            if($account->new_password != '') {
                $account->password = sha1($account->new_password);
            }

            if(!Yii::app()->request->isAjaxRequest && $account->save()) {
                $this->redirect(['account/manage']);
            }
        }

        if(Yii::app()->request->isAjaxRequest) {
            echo CActiveForm::validate($account);
            Yii::app()->end();
        }

        $this->render('create', array(
            'account' => $account
        ));
    }

    public function actionIndex()
    {
        $this->redirect(['booking/manage']);
    }

    public function actionAbout()
    {
        echo 'test';
    }

    public function actionError()
    {
        $error = Yii::app()->errorHandler->error;
        if(Yii::app()->request->isAjaxRequest)
            echo $error['message'];
        else
            $this->render('error', $error, FALSE, TRUE);
    }

    public function actionLogin()
    {
        $account = new UserAccount('login');
        $account->unsetAttributes();

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($account);
            Yii::app()->end();
        }

        if(isset($_POST['UserAccount'])) {
            $account->setAttributes($_POST['UserAccount']);
            if($account->validate() && $account->login()) {
                $this->redirect(['account/index']);
            }
        }

        $this->render('login', array(
            'account' => $account
        ));
    }

    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(array('account/index'));
    }

    public function actionSales()
    {
        $query = null;
        if(isset($_GET['query'])) {
            $query = $_GET['query'];
        }

        $criteria = new CDbCriteria();
        $criteria->condition = 'realname LIKE :query AND division = 2';
        $criteria->params = [':query' => "%$query%"];
        $account = UserAccount::model()->findAll($criteria);

        $result = array();
        foreach($account as $a) {
            $result[] = [
                'name' => $a->realname,
                'code' => $a->identity,
                'value' => $a->id
            ];
        }

        header('Content-type: application/json');
        echo json_encode($result);
    }
}

protected/controllers/BookingController.php
<?php

/**
 * Class BookingController
 *
 * @author Niko Wicaksono <wicaksono@nodews.com>
 */
class BookingController extends Controller
{
    public $defaultAction = 'manage';

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'roles'   => [UserAccount::IT, UserAccount::TF, UserAccount::AI],
                'actions' => ['manage', 'create', 'update', 'delete']
            ),
            array(
                'deny',
                'users' => ['*']
            )
        );
    }

    public function actionCreate()
    {
        $booking = new CommBooking('create');
        $booking->unsetAttributes();

        if(isset($_POST['CommBooking'])) {
            $booking->setAttributes($_POST['CommBooking']);

            // @fixme ua_id
            $booking->ua_id = Yii::app()->user->id;
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($booking);
            Yii::app()->end();
        }

        if(isset($_POST['CommBooking']) && !isset($_POST['ajax'])) {
            if($booking->save()) {
                $this->redirect(['booking/update', 'id' => $booking->id]);
            }
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('create', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('create', [
                'booking' => $booking
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $booking = CommBooking::model()->findByPk($id);
        if(is_null($booking)) throw new CHttpException(403, 'Not Found');
        if($booking->stat == CommBooking::STAT_DONE) $this->redirect(['/booking/manage']);

        if(isset($_POST['CommBooking'])) {
            $booking->setAttributes($_POST['CommBooking']);
            $booking->ua_id = Yii::app()->user->id;

            $booking->save();
        }

        if(isset($_POST['ajax'])) {
            echo CActiveForm::validate($booking);
            Yii::app()->end();
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('update', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('update', [
                'booking' => $booking
            ]);
        }
    }

    public function actionDelete($id)
    {
        $booking = CommBooking::model()->findByPk($id);
        if(!is_object($booking)) throw new CHttpException('Not Found');

        CommBooking::model()->deleteByPk($id);
    }

    public function actionManage()
    {
        $booking = new CommBooking('manage');
        $booking->unsetAttributes();

        if(isset($_GET['CommBooking'])) {
            $booking->setAttributes($_GET['CommBooking']);
        }

        if(Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('manage', [
                'booking' => $booking
            ], false, true);
        } else {
            $this->render('manage', [
                'booking' => $booking
            ]);
        }
    }
}

protected/views/layouts/main.php
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/fonts/ubuntu.css" rel="stylesheet" type="text/css">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/css/bootstrap.css" rel="stylesheet" type="text/css">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/css/jquery-ui.css" rel="stylesheet" type="text/css">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/css/select2.css" rel="stylesheet" type="text/css">
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/jquery.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/jquery-ui.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/jquery.select2.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/hogan.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/bootstrap.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/typeahead.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/yii/gridview.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/assets/static/js/yii/activeform.js"></script>
        <?php Yii::app()->getClientScript()->registerCoreScript('bbq'); ?>
        <?php Yii::app()->getClientScript()->registerCoreScript('yiiactiveform'); ?>
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
        <?php Yii::app()->getClientScript()->registerScript('init', '
            jQuery(function($) {
                $.datepicker.setDefaults({
                    dateFormat: "yy-mm-dd",
                    defaultDate: "0000-00-00",
                    showOn: "focus",
                    showButtonPanel: true,
                    changeMonth: true,
                    changeYear: true,
                    buttonImageOnly: true,
                    showButtonPanel: false
                });
            });
            function _afterAjaxUpdate(id, data) {
                $(".datepicker").datepicker();
            };
        ', CClientScript::POS_END); ?>
        <style>
            body {
                font-family: 'Ubuntu Condensed';
                font-weight: 400;
            }
            .filters input,
            .filters select {
                display: block;
                width: 100%;
                height: 24px;
                padding: 0 2px;
                font-size: 12px;
                line-height: 1.428571429;
                color: #555555;
                vertical-align: middle;
                background-color: #ffffff;
                background-image: none;
                border: 1px solid #cccccc;
                -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
                box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
                -webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
                transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
            }
            .form-control {
                border-radius: 0;
            }
            .grid-view tbody tr td,
            .grid-view thead tr th {
                text-align: center;
            }
            .grid-view table.items th,
            .grid-view .button-column {
                white-space: nowrap;
            }
            .partiture-image {
                list-style: none;
            }
            .partiture-image li {
                float: left;
                margin: 10px;
            }

            .placing-pagination {
                list-style: none;
            }
            .placing-pagination li {
                float: left;
                margin-left: 10px;
            }

            .tt-hint {
                color: #fff
            }

            .tt-dropdown-menu {
                width: 422px;
                margin-top: 12px;
                padding: 8px 0;
                background-color: #fff;
                border: 1px solid #ccc;
                border: 1px solid rgba(0, 0, 0, 0.2);
                -webkit-border-radius: 8px;
                -moz-border-radius: 8px;
                border-radius: 8px;
                -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
                -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
                box-shadow: 0 5px 10px rgba(0,0,0,.2);
            }

            .tt-suggestion {
                padding: 3px 20px;
            }

            .tt-suggestion.tt-is-under-cursor {
                color: #fff;
                background-color: #0097cf;

            }

            .tt-suggestion p {
                margin: 0;
            }
        </style>
    </head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:;"><?php echo Yii::app()->name; ?></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <?php if(Yii::app()->user->isGuest): ?>
                    <?php else: ?>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">Booking <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><?php echo CHtml::link('Create', ['booking/create']); ?></li>
                            <li><?php echo CHtml::link('Manage', ['booking/manage']); ?></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Request</li>
                            <li><?php echo CHtml::link('Browse', ['request/browse']); ?></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">Partitur <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><?php echo CHtml::link('Create', ['placing/browse']); ?></li>
                            <li><?php echo CHtml::link('Report', ['placing/report']); ?></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Dateset</li>
                            <li><?php echo CHtml::link('Create', ['dateset/create']); ?></li>
                            <li><?php echo CHtml::link('Manage', ['dateset/manage']); ?></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Resource</li>
                            <li><?php echo CHtml::link('Coordinate', Yii::app()->request->baseUrl . '/pageset.pdf'); ?></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><?php echo CHtml::link('Create', ['account/create']); ?></li>
                            <li><?php echo CHtml::link('Manage', ['account/manage']); ?></li>
                        </ul>
                    </li>
                    <?php endif; ?>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <?php if(Yii::app()->user->isGuest): ?>
                    <li><?php echo CHtml::link('Login', ['account/login']); ?></li>
                    <?php else: ?>
                    <li>
                        <li class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><?php echo Yii::app()->user->account->username; ?> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><?php echo CHtml::link('Logout', ['account/logout']); ?></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Setting</li>
                                <li><?php echo CHtml::link('Change Password', ['dateset/create']); ?></li>
                            </ul>
                        </li>
                    </li>
                    <?php endif; ?>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1><?php echo CHtml::encode($this->pageTitle); ?></h1>
            </div>
        </div>
        <?php echo $content; ?>
    </div>

</body>
</html>